name: example
description: Autoequal example
version: 1.0.0

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  autoequal: ^0.4.1

dev_dependencies:
  pedantic: ^1.11.1
  build_runner: ^2.2.0
  autoequal_gen: ^0.4.1
  test: ^1.19.3

dependency_overrides:
  autoequal:
    path: ../autoequal
  autoequal_gen:
    path: ../autoequal_gen