name: autoequal
description: |
  Annotations for code generator 'autoequal_gen' to simplify work with 'equatable'.
  It will generate 'List<Object?> props' private extensions for all annotated classes.
version: 0.7.1
homepage: https://github.com/sunnydaydev/autoequal

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  meta: ^1.9.1

dev_dependencies:
  equatable: ^2.0.5
  lints: ">=2.1.1 <4.0.0"
  test: ^1.21.5