targets:
  $default:
    builders:
      autoequal_gen:
        enabled: true
        options:
          include_getters: false

builders:
  autoequal_gen:
    target: "autoequal_gen"
    import: "package:autoequal_gen/autoequal_gen.dart"
    builder_factories: ["autoequalGenerator"]
    build_extensions: {".dart": [".autoequal.g.part"]}
    auto_apply: dependents
    build_to: cache
    applies_builders: ["source_gen|combining_builder"]