name: autoequal_gen
description: |
  Codegenerator which can simplify work with 'equatable'.
  It will generate 'List<Object?> props' priviate extensions for all annotated classes.
version: 0.4.0
homepage: https://github.com/sunnydaydev/autoequal

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  analyzer: ^4.7.0
  build: ^2.3.0
  source_gen: ^1.2.2
  autoequal: ^0.4.0
  equatable: ^2.0.5

dev_dependencies:
  build_test: ^2.1.5
  build_runner: ^2.2.0
  test: ^1.21.5
  pedantic: ^1.11.1
