name: autoequal_gen
description: |
  Code generator which can simplify work with 'equatable'.
  It will generate 'List<Object?> props' private extensions for all annotated classes.
version: 0.7.0
homepage: https://github.com/sunnydaydev/autoequal

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  analyzer: '>=4.7.0 <7.0.0'
  build: ^2.4.1
  source_gen: ^1.4.0
  autoequal: ^0.6.0
  equatable: ^2.0.5
  code_builder: ^4.7.0
  dart_style: ^2.3.3

dev_dependencies:
  build_test: ^2.2.1
  build_runner: ^2.4.6
  lints: ^3.0.0
  test: ^1.24.9
