name: example
description: Autoequal example
version: 1.0.0

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  autoequal: ^0.6.0
  equatable: ^2.0.5

dev_dependencies:
  build_runner: ^2.2.0
  autoequal_gen: ^0.6.0
  lints: ">=2.1.1 <4.0.0"
  test: ^1.21.5

dependency_overrides:
  autoequal:
    path: ../autoequal
  autoequal_gen:
    path: ../autoequal_gen